"""add organisation

Revision ID: fc6ee1027637
Revises: 253f2da17939
Create Date: 2023-07-13 15:47:42.292970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc6ee1027637"
down_revision = "253f2da17939"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisation",
        sa.Column("entity", sa.BigInteger(), nullable=False),
        sa.Column("organisation", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("entity"),
    )
    with op.batch_alter_table("planning_application", schema=None) as batch_op:
        batch_op.create_foreign_key(
            None, "organisation", ["organisation_entity"], ["entity"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("planning_application", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    op.drop_table("organisation")
    # ### end Alembic commands ###
